In [19]:
import numpy as np

operand1 = np.array([1, 2, 3, 4, 5])
operand2 = np.array([5, 4, 3, 2, 1])
print(operand1 + operand2)

operand1 = [1, 2, 3, 4, 5]
operand2 = [5, 4, 3, 2, 1]
print(operand1 + operand2)

# Python list는 vector operation이나 matrix operation과는 근본적으로 거리가 있는 data structure인 것이다.

operand1 = np.array([1, 2, 3, 4, 5])
operand2 = np.array([5, 4, 3, 2, 1])
print(operand1 - operand2)

[6 6 6 6 6]
[1, 2, 3, 4, 5, 5, 4, 3, 2, 1]
[-4 -2  0  2  4]


In [20]:
# Vector and Scalar
# 위의 연산 외에도 NumPy는 생각보다 똑똑해서 수학적이지 않는 표현들까지도 연산이 가능하다.
# 만약 우리가 어떤 vector에 scalar를 더하면 수학적으로 정의되지 않는다는 것을 알고 있다.
# 하지만 이를 NumPy 입장에서 오류로 처리해버린다면 이는 연산자를 낭비하는 것이며 이를 우리가 Vector에 모두 같은 scalar를 더하거나 빼는 것으로 약속한다면 훨씬 간단하게 arithmetic operation을 수행할 수 있게 된다.
operand1 = np.array([1, 2, 3, 4, 5])
operand2 = 10

print(operand1 + operand2, '\n')
print(operand1 - operand2, '\n')

operand1 = np.random.randint(low = 0, high = 10, size = (2,3))
print(operand1, '\n')
print(operand1 + 10, '\n')
print(operand1 - 10, '\n')

[11 12 13 14 15] 

[-9 -8 -7 -6 -5] 

[[4 7 0]
 [5 7 7]] 

[[14 17 10]
 [15 17 17]] 

[[ -6  -3 -10]
 [ -5  -3  -3]] 



In [21]:
# 다음 broadcating은 Matrix에 Vector 연산을 하는 경우이다.

operand1 = np.random.randint(low = 0, high = 10, size = (2,3))
operand2 = np.array([[10], [20]])

print("====== Original Operands =======")
print(operand1, '\n')
print(operand2, '\n')
print("operand1.shape:", operand1.shape, "operand2.shape:", operand2.shape, '\n')

print(operand1 + operand2, '\n')
print(operand1 - operand2, '\n')

#위에서 주목할 점은 먼저 operand들의 shape이다. 하나는 (2,3)이고 다른 하나는 (2,1)이다.
#이 상태에서 arithmetic operation을 시키면 NumPy는 operand2를 (2,1)을 복사하여 (2,3)으로 자동으로 변화시킨다.
#그리고 (2,3)의 operand1과 복사된 (2,3)의 operand2를 연산하는 것이다.

====== Original Operands =======
[[4 5 1]
 [5 4 4]] 

[[10]
 [20]] 

operand1.shape: (2, 3) operand2.shape: (2, 1) 

[[14 15 11]
 [25 24 24]] 

[[ -6  -5  -9]
 [-15 -16 -16]] 



In [22]:
operand1 = np.random.randint(low = 0, high = 10, size = (2,3))
operand2 = np.array([10, 20, 30])

print("====== Original Operands =======")
print(operand1, '\n')
print(operand2, '\n')
print("operand1.shape:", operand1.shape, "operand2.shape:", operand2.shape, '\n')

print(operand1 + operand2, '\n')
print(operand1 - operand2, '\n')

====== Original Operands =======
[[1 4 2]
 [9 0 6]] 

[10 20 30] 

operand1.shape: (2, 3) operand2.shape: (3,) 

[[11 24 32]
 [19 20 36]] 

[[ -9 -16 -28]
 [ -1 -20 -24]] 



In [23]:
operand1 = 10
operand2 = 3

print(operand1 * operand2)
print(operand1 / operand2)
print(operand1 % operand2)

30
3.3333333333333335
1


In [24]:
operand1 = [10, 20, 30, 40, 50]
operand2 = [3, 3, 3, 3, 3]

print(operand1 * operand2)
print(operand1 / operand2)
print(operand1 % operand2)
#위에서 볼 수 있듯이, python list는 말그대로 list이고 vector가 아니기 때문에 우리가 원하는 결과를 얻기 힘들다.

TypeError: ignored

In [25]:
operand1 = [10, 20, 30, 40, 50]
operand2 = 3

print(operand1 * operand2)
print(operand1 / operand2)
print(operand1 % operand2)
# NumPy를 이용하지 않고 이런 vector operation을 할 수 없다.

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50, 10, 20, 30, 40, 50]


TypeError: ignored

In [26]:
operand1 = np.array([10, 20, 30, 40, 50])
operand2 = 3

print(operand1 * operand2)
print(operand1 / operand2)
print(operand1 % operand2)
#ndarray의 *연산은 우리가 아는 veoctor의 dot product가 아니다. 각각 element마다의 연산을 해주는 element-wise operation이라는 것을 꼭 기억하자.

operand1 = np.random.randint(low = 0, high = 10, size = (3,4))
operand2 = np.array([3, 4, 5]).reshape(3,1)

print("====== Original Operands =======")
print("operand1:\n", operand1)
print("operand2:\n", operand2)

print("operand1.shape:", operand1.shape, "operand2.shape:", operand2.shape,  '\n\n')

print("operand1 * operand2:\n", operand1 * operand2)
print("operand1 / operand2:\n", operand1 / operand2)
print("operand1 % operand2:\n", operand1 % operand2)

[ 30  60  90 120 150]
[ 3.33333333  6.66666667 10.         13.33333333 16.66666667]
[1 2 0 1 2]
====== Original Operands =======
operand1:
 [[2 9 2 4]
 [5 3 0 2]
 [6 6 9 6]]
operand2:
 [[3]
 [4]
 [5]]
operand1.shape: (3, 4) operand2.shape: (3, 1) 


operand1 * operand2:
 [[ 6 27  6 12]
 [20 12  0  8]
 [30 30 45 30]]
operand1 / operand2:
 [[0.66666667 3.         0.66666667 1.33333333]
 [1.25       0.75       0.         0.5       ]
 [1.2        1.2        1.8        1.2       ]]
operand1 % operand2:
 [[2 0 2 1]
 [1 3 0 2]
 [1 1 4 1]]
