In [2]:
import numpy as np

python_list = [1, 2, 3, 4, 5]
print(python_list[3]) # Python list indexing
print(python_list[2:5]) # Python list slicing

test_np = np.array([1, 2, 3, 4, 5])
print(test_np[3]) # ndarray indexing
print(test_np[2:5]) # ndarray slicing

python_matrix = [[1, 2], [3, 4], [5, 6], [7, 8]]
print(python_matrix)

print(python_matrix[0])
print(python_matrix[1])
print(python_matrix[0:3])

4
[3, 4, 5]
4
[3 4 5]
[[1, 2], [3, 4], [5, 6], [7, 8]]
[1, 2]
[3, 4]
[[1, 2], [3, 4], [5, 6]]


In [5]:
python_matrix = [[1, 2], [3, 4], [5, 6], [7, 8]]
print(python_matrix)

#print(python_matrix[1,1]) #에러발생
print(python_matrix[1]) # 두 번째 원소에 접근하고 이 원소는 다시 python list를 가짐
print(python_matrix[1][1]) # 이 python list [3,4]에 대해 다시 한 번 indexing을 해줘야 함

 #python list는 말그대로 list일 뿐이지 matrix나 tensor를 다루는 방법이 아닌 것이다.

[[1, 2], [3, 4], [5, 6], [7, 8]]
[3, 4]
4


In [7]:
python_matrix = [[1, 2], [3, 4], [5, 6], [7, 8]]
nd_matrix = np.array(python_matrix)

print(nd_matrix, '\n')
print("nd_matrix[0]:", nd_matrix[0])
print("nd_matrix[1]:", nd_matrix[1])
print("nd_matrix[0:3]:\n", nd_matrix[0:3])

#ndarray는 파이썬 리스트와는 다르게 우리가 수학적으로 다루는 (m,n)-th entry에 접근하는 방법이 가능하다. 
print("nd_matrix[0,0]:", nd_matrix[0,0])
print("nd_matrix[3,1]:", nd_matrix[3,1])

#또한 ndarray는 말그대로 vecot, matrix, tensor에 최적화 되있는 data type이므로 다음과 같은 indexing, slicing이 가능하다.                
print("nd_matrix[0,0]:", nd_matrix[:,0])
print("nd_matrix[3,1]:", nd_matrix[:,1])

#즉, 첫 번째 column과 두 번째 column을 뽑아내는 방법도 python list에서 사용하는 indexing, slicing을 이용하여 구할 수 있게 된다.
# 이처럼 python list보다 ndarray는 우리가 수학적으로 data를 다루는 방법에 더 친화적이며 이를 통해 불필요한 코딩들을 할 필요가 없어지는 장점이 있다.

[[1 2]
 [3 4]
 [5 6]
 [7 8]] 

nd_matrix[0]: [1 2]
nd_matrix[1]: [3 4]
nd_matrix[0:3]:
 [[1 2]
 [3 4]
 [5 6]]
nd_matrix[0,0]: 1
nd_matrix[3,1]: 8
nd_matrx 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]] 

nd_matrix[0,0]: [1 3 5 7]
nd_matrix[3,1]: [2 4 6 8]


In [8]:
#예를 들어, 다음과 같이 H=1080, W=1920, C=3(RGB channel)의 모양을 가지는 ndarray가 있다고 가정해보자.

img = np.random.randint(low = 0, high = 255, size = (1080, 1920, 3))
print(img.shape)

R_channel = img[:,:,0]
G_channel = img[:,:,1]
B_channel = img[:,:,2]

print("R_channel.shape:", R_channel.shape)
print("G_channel.shape:", G_channel.shape)
print("B_channel.shape:", B_channel.shape)

(1080, 1920, 3)
R_channel.shape: (1080, 1920)
G_channel.shape: (1080, 1920)
B_channel.shape: (1080, 1920)


In [16]:
#python list에서 indexing, slicing을 하면 복사본을 만들지만 다량의 data를 다루고,
#indexing과 slicing이 빈번히 일어나는 ndarray에서는 indexing, slicing을 하면 새로운 ndarray를 만드는 것이 아니라 
#기존 ndarray에 참조를 하므로 기존 ndarray에 영향을 미칠 수 있다.

#먼저 python list의 indexing에 대해서 살펴보자.
python_list = [[1,2],[3,4]]

print("original python_list:", python_list, '\n')
element1 = python_list[0] # 첫 번째 원소 추출
python_list[0] = [10,10] # 원래의 python list의 첫 번째 원소들을 10으로 바꿈

print("python_list:", python_list)
print("element1:", element1)
#먼저 첫 번째 element를 뽑아내면 새로운 memory에 element1가 할당되기 때문에 
#기존 python_list를 수정해도 element1에는 영향을 미치지 않는다.

#하지만 ndarray는 다른 결과를 보여준다.
np_arr = np.array([[1,2],[3,4]])

print("original np_arr:", np_arr, '\n')
element1 = np_arr[0] # 첫 번째 원소 추출
np_arr[0] = [10, 10] # 원래의 ndarray의 첫 번째 원소들을 10으로 바꿈

print("nd_arr:\n", np_arr)
print("element1:", element1)
#분명 element1를 수정한 적이 없는데도 마지막 줄에서 확인할 수 있듯이 np_arr를 수정하니 element1도 같이 수정되었다.

#ndarray는 큰 data를 다루고, indexing과 slicing이 빈번히 일어나므로 최대한 memory를 아끼려는 모습을 보여준다.
#이 때문에 불필요하게 새로운 ndarray를 만들지 않고 참조를 이용하여 indexing, slicing을 한다.
#이런 ndarray의 철학 덕분에 큰 data를 다룰 때 우리가 가진 RAM을 효율적으로 쓸 수 있지만, 기존 ndarray를 수정하면 indexing, slicing된 data에 영향을 미치므로 예기치 않은 결과를 얻을 수 있다는 단점이 있다.
#따라서 보통 indexing, slicing을 할 때 copy()함수를 함께 이용한다.
np_arr = np.array([[1,2],[3,4]])

print("original np_arr:", np_arr, '\n')
element1 = np_arr[0].copy() # 첫 번째 원소 추출
np_arr[0] = [10, 10] # 원래의 ndarray의 첫 번째 원소들을 10으로 바꿈

print("nd_arr:\n", np_arr)
print("element1:", element1)

original python_list: [[1, 2], [3, 4]] 

python_list: [[10, 10], [3, 4]]
element1: [1, 2]
original np_arr: [[1 2]
 [3 4]] 

nd_arr:
 [[10 10]
 [ 3  4]]
element1: [10 10]
original np_arr: [[1 2]
 [3 4]] 

nd_arr:
 [[10 10]
 [ 3  4]]
element1: [1 2]


In [32]:
import numpy as np
np.random.seed(0)
 
#먼저 알아둬야 할 것은 reshape, resize가 각각 2개의 method를 가지고 있다. 이를 각각 살펴보면
#1.numpy.reshape
#2.numpy.resize
#3.ndarray.reshape
#4.ndarray.resize

#이렇게 4가지고 있고, numpy로 시작하는 함수들은
#np.reshape, np.resize
#위와 같이 사용하는 함수들이고, 만약 test_np라는 ndarray가 있을 때 ndarray.reshape, ndarray.resize method들은
#test_np.reshape, test_np.resize
#위와 같이 사용하는 method들이다. 따라서 np.으로 시작하는 함수들은 어떤 ndarray에 대해 reshape, resize를 할지 정해줘야 하지만
#test_np.로 시작하는 reshape, resize는 이미 test_np라는 ndarray에 대해 reshape, resize를 해준다는 뜻이 담겨있으므로 target ndarray를 지정해줄 필요가 없다.
#따라서 np.보다는 test_np.와 같이 ndarray에 대한 method를 자주 사용한다.
test_np = np.random.randint(low = 0, high = 3, size = (4,5))
print(test_np,'\n')

reshaped_np = test_np.reshape(5,4)
print(reshaped_np,'\n')

reshaped_np2 = test_np.reshape(2,10)
print(reshaped_np2,'\n')

[[0 1 0 1 1]
 [2 0 2 0 0]
 [0 2 1 2 2]
 [0 1 1 1 1]] 

[[0 1 0 1]
 [1 2 0 2]
 [0 0 0 2]
 [1 2 2 0]
 [1 1 1 1]] 

[[0 1 0 1 1 2 0 2 0 0]
 [0 2 1 2 2 0 1 1 1 1]] 



In [29]:
resized_np = test_np.resize(5,4)
print(resized_np)
#https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.resize.html#numpy.ndarray.resize
#에서 알 수 있듯이 return value가 None이다. 
print(test_np)
 #원래 (4,5) ndarray가 (5,4)로 바뀐 것을 알 수 있다. 이렇게 ndarray.resize() method는 원래의 ndarray를 바꿔주는, 즉 in-place 작용을 하는 것을 알 수 있다.

 

None
[[100 100 100 100]
 [100   2   1   0]
 [  1   2   0   0]
 [  2   0   0   0]
 [  0   0   0   2]]


In [39]:
test_np = np.random.randint(low = 0, high = 3, size = (4,5))
print("original test_np:\n", test_np, '\n')

reshaped_np = test_np.reshape(5,4) # reshaped ndarray 생성
test_np[0] = 100 # test_np의 첫 번째 row를 모두 100으로 치환
print("test_np:\n", test_np, '\n')
print("reshaped_np:\n:", reshaped_np, '\n')


original test_np:
 [[2 1 0 0 0]
 [0 0 1 0 2]
 [2 2 0 0 2]
 [0 2 2 0 1]] 

test_np:
 [[100 100 100 100 100]
 [  0   0   1   0   2]
 [  2   2   0   0   2]
 [  0   2   2   0   1]] 

reshaped_np:
: [[100 100 100 100]
 [100   0   0   1]
 [  0   2   2   2]
 [  0   0   2   0]
 [  2   2   0   1]] 

original test_np:
 [[1 1 0 0 1]
 [0 0 1 2 2]
 [0 2 1 1 2]
 [1 2 2 1 2]] 

test_np:
 [[100 100 100 100 100]
 [  0   0   1   2   2]
 [  0   2   1   1   2]
 [  1   2   2   1   2]] 

reshaped_np:
: [[1 1 0 0]
 [1 0 0 1]
 [2 2 0 2]
 [1 1 2 1]
 [2 2 1 2]] 



In [40]:
test_np = np.random.randint(low = 0, high = 3, size = (4,5))
print("original test_np:\n", test_np, '\n')
reshaped_np = test_np.reshape(5,4).copy() # reshaped ndarray 생성
test_np[0] = 100 # test_np의 첫 번째 row를 모두 100으로 치환

print("test_np:\n", test_np, '\n')
print("reshaped_np:\n:", reshaped_np, '\n')

original test_np:
 [[0 0 2 1 1]
 [2 2 1 0 2]
 [0 2 0 2 1]
 [2 1 0 1 1]] 

test_np:
 [[100 100 100 100 100]
 [  2   2   1   0   2]
 [  0   2   0   2   1]
 [  2   1   0   1   1]] 

reshaped_np:
: [[0 0 2 1]
 [1 2 2 1]
 [0 2 0 2]
 [0 2 1 2]
 [1 0 1 1]] 



In [ ]:
#reshaped는 copy와 함께 사용하면 기존의 ndarray를 다른 shape을 가진 ndarray로 만들어 연산을 진행할 수 있다.
#반면에 resize() method는 in-place 작용을 한다고 했으므로 현재 가지고 있는 ndarray를 resize하고 다시 돌려놓을 필요가 없을 때 사용한다. 예를 들어
#우리가 처음 받은 data의 모양이 마음에 들지 않을 때 우리는 resizing을 하게 된다. 
#그리고 이 resizing은 다음에 다시 돌려놓을 필요가 없으므로 이 in-place resize() method를 이용하면 코드도 더 간단하면서도 reshape() method와 같은 역할을 수행할 수 있다.

In [45]:
digit1 = np.zeros(shape = (28,28))
print(digit1.shape,'\n')

vec_digit1 = digit1.reshape(784,1)
print(digit1.shape)
print(vec_digit1.shape,'\n')
#하지만 위와 같이 설정하면 다른 크기의 image를 받을 때 계속 코드를 바꿔주어야 한다. 하지만 -1을 이용하면 다음과 같다.
vec_digit1 = digit1.reshape(-1,1)
print(digit1.shape)
print(vec_digit1.shape,'\n')
# 즉 -1은 reshape을 할 때 다른 차원을 먼저 맞춰주고 그에 맞게 -1을 쓴 차원을 맞춰준다.
# 우리가 2번째 차원을 1로 fix시켰으므로 원소의 개수가 맞기 위해선 첫 번재 차원이 784가 돼야하는 것이다.
# 이렇게 -1을 사용하면 vectorization의 입장에서 동일한 결과를 얻을 수 있지만 image가 28x28일 때를 제외하더라도 계속 사용할 수 있다는 장점이 있다.
# 또한 무엇보다 편리하게 vectorization을 할 수 있다.

(28, 28) 

(28, 28)
(784, 1) 

(28, 28)
(784, 1) 

